# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-17 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191217_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='owner',
        ),
    ]
