# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-23 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_content_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=models.CharField(max_length=1024, verbose_name='摘要'),
        ),
    ]
