# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-28 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='cerated_time',
            new_name='created_time',
        ),
    ]
